title:            JRichardsz
description:      java, software, maths, ia, projects ,animes and series.
logo:             site-logo.png
disqus_shortname: jrichardsz-github-io
search:           true
#Change url to your domain. Leave localhost server or blank when working locally.
url:        https://jrichardsz.github.io      
#cdn:			  http://cdn.localhost:4000

# Owner/author information
owner:
  name:				Richard Osmar Leon Ingaruca
  avatar:			bio-photo.jpg
  email:			you@email.com
  signoff_text:		Hasta la pr√≥xima vez
  signoff_link:		/about
  signature_image:	signature.png
  # Social networking links used in footer. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        JRichardsz
  facebook:       
  github:         jrichardsz
  stackexchange:  http://stackoverflow.com/users/3957754/jrichardsz
  linkedin:       richard-osmar-leon-ingaruca-65569b94
  instagram:      
  flickr:         
  tumblr:         
  hmfaysalsocial: 
  youtube: https://www.youtube.com/user/ZERL1NG
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: T-Details
    url: /technical-details
  - title: Tags
    url: /tags
  - title: Categories
    url: /categories
  - title: Blog
    url: /
    external: false
  - title: About
    url: /about


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    false
highlight_js:	false
markdown:    kramdown
paginate:    4
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  syntax_highlighter: rouge
  highlighter: rouge

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: [".gitignore", "build.bat", "build-deploy.bat", "build-init.bat", "desktop.ini", "post.thor",  "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
